// <auto-generated />
namespace DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.9.12")]
    public sealed partial class _2021020501 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2021020501));
        
        string IMigrationMetadata.Id
        {
            get { return "202102050506011_2021020501"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
