// <auto-generated />
namespace DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.9.12")]
    public sealed partial class _2021013103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2021013103));
        
        string IMigrationMetadata.Id
        {
            get { return "202101310111058_20210131-03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
